---
services:
  cloudflared:
    image: cloudflare/cloudflared:2026.10.0@sha256:9b49eed8f62806d5d45ddf59ecefb5710429598ea6d3fcccd2af938f621b2b07
    container_name: cloudflared
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    extra_hosts:
      - host.docker.internal:host-gateway
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_METRICS=localhost:60123
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "--metrics", "localhost:60123", "ready"]
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 10s
    networks:
      - cloudflared-gw
      - app-infra

networks:
  cloudflared-gw:
    driver: bridge
  app-infra:
    external: true
