---
docker_stacks:
  webmail:
    env_file: false
    state: stopped
  roundcube:
    env_file: true
    state: present
  calcom:
    env_file: true
    state: present
  open-webui:
    env_file: true
    state: present
  1min-relay:
    env_file: true
    state: present
  twenty:
    env_file: true
    state: present
