---
wireguard_address: "10.253.0.1/24"
wireguard_port: 51820

# List of peers to configure on the hub.
# Each entry: { name: str, public_key: str, allowed_ips: str }
# Example:
#   - name: admin-laptop
#     public_key: "abc123...="
#     allowed_ips: "10.253.0.2/32"
wireguard_peers:
    - name: giraffe
      public_key: "WOohRZe1nb1O3XX6GY3mPvw3rcyoLlsZTg0NtNkKhjs="
      allowed_ips: "10.253.0.2/32"
    - name: cetriolo
      public_key: "UwTPvGJI408lgMiH4T0Js/xy39zwkR5Jx4cCqBtl/30="
      allowed_ips: "10.253.0.3/32"
    - name: ostrich
      public_key: "yoiZEbKP8H8ArVBKQRk816fr11Xtx4s1A7H+stPdg3s="
      allowed_ips: "10.253.0.4/32"
