---
- name: Update apt cache, dist-upgrade, and autoremove
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    autoremove: true
    purge: true

- name: Install extrepo
  ansible.builtin.apt:
    name: extrepo
    state: present

- name: Enable mise repository
  ansible.builtin.command: extrepo enable mise
  args:
    creates: /etc/apt/sources.list.d/extrepo_mise.sources

- name: Install mise
  ansible.builtin.apt:
    name: mise
    state: present
    update_cache: true

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists
