---
services:
  roundcubemail:
    image: roundcube/roundcubemail:1.7.4-apache@sha256:93c6ccb63ce2feccb107c0eca128f8625ac4c3e9e42329e44d0a60da66a70a40
    container_name: roundcubemail
    restart: unless-stopped
    tmpfs:
      - /tmp
    volumes:
      - ./www:/var/www/html
      - ./db/sqlite:/var/roundcube/db
    ports:
      - "127.0.0.1:3002:80"
    env_file:
      - .env
    networks:
      - app-infra

networks:
  app-infra:
    external: true
