services:
  roundcubemail:
    image: roundcube/roundcubemail:1.7.4-apache@sha256:592b09d61171bf0bddb65cb2f7820cab58762793b309f6513f4cdec7ac23838f
    container_name: roundcubemail
    restart: unless-stopped
    tmpfs:
      - /tmp
    volumes:
      - ./www:/var/www/html
      - ./db/sqlite:/var/roundcube/db
    ports:
      - "127.0.0.1:3002:80"
    env_file:
      - .env
    networks:
      - app-infra

networks:
  app-infra:
    external: true
