---
services:
  roundcubemail:
    image: roundcube/roundcubemail:1.7.4-apache@sha256:1162705d5fa6514e6dc2eb71896c208fc3cae35b9cb49019ae23e3cbd9eab79b
    container_name: roundcubemail
    restart: unless-stopped
    tmpfs:
      - /tmp
    volumes:
      - ./www:/var/www/html
      - ./db/sqlite:/var/roundcube/db
    ports:
      - "127.0.0.1:3002:80"
    env_file:
      - .env
    networks:
      - app-infra

networks:
  app-infra:
    external: true
