services:
  database:
    image: postgres:18-alpine@sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - calcom

  calcom:
    image: calcom/cal.com:v6.2.0@sha256:ace3bb1219fb7306585ab9f4d94d41af7ee064c343db0498173436bbe857bd49
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "127.0.0.1:3003:3000"
    env_file:
      - .env
    networks:
      - calcom
      - app-infra

volumes:
  database:
    driver: local

networks:
  calcom:
    driver: bridge
  app-infra:
    external: true
