services:
  cobalt-api:
    image: ghcr.io/imputnet/cobalt:11.7.1@sha256:63186dd68afd57ce3bb1f62cc4c139f5fa95b9c3e87a3cf5c6e4c7a570523f62
    container_name: cobalt-api
    restart: unless-stopped
    init: true
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    env_file: .env
    networks:
      - app-infra
    volumes:
      - ./keys.json:/app/keys.json:ro

networks:
  app-infra:
    external: true
