---
- name: Setup Authentik Infrastructure
  block:
    - name: Create authentik directories
      file:
        path: "/opt/containers/authentik/{{ item }}"
        state: directory
        owner: "1000"
        group: "1000"
        mode: '0755'
      loop:
        - media
        - custom-templates
        - certs

    - name: Check if Authentik .env file exists
      stat:
        path: /opt/containers/authentik/.env
      register: authentik_env_file

    - name: Deploy Authentik docker-compose stack
      community.docker.docker_compose_v2:
        project_src: "/opt/containers/authentik"
        state: present
        pull: "always"
        wait: true
        wait_timeout: 300
      when: authentik_env_file.stat.exists

    - name: Show message when .env file is missing
      debug:
        msg: "Authentik .env file does not exist - skipping deployment"
      when: not authentik_env_file.stat.exists
