services:
  webmail:
    image: ghcr.io/linagora/tmail-web:release@sha256:cd9553edd9779cab08ed4ccab470aaba19fdb16fe6bd87296777027c3dd9cb22
    container_name: webmail
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run
    ports:
      - "127.0.0.1:3001:80"
    volumes:
      - ./env.file:/usr/share/nginx/html/assets/env.file
    networks:
      - app-infra

networks:
  app-infra:
    external: true
