services:
  webmail:
    image: ghcr.io/linagora/tmail-web:release@sha256:88f46d5a9ab2a38ab4d6a0d808c96637586806188dcb08684a3927806449304e
    container_name: webmail
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run
    ports:
      - "127.0.0.1:3001:80"
    volumes:
      - ./env.file:/usr/share/nginx/html/assets/env.file
    networks:
      - app-infra

networks:
  app-infra:
    external: true
