services:
  webmail:
    image: ghcr.io/linagora/tmail-web:release@sha256:84aa5567c1fab5aaa4a708ec4a99faff6344d266f2985252aa44e13483be1a0a
    container_name: webmail
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run
    ports:
      - "127.0.0.1:3001:80"
    volumes:
      - ./env.file:/usr/share/nginx/html/assets/env.file
    networks:
      - app-infra

networks:
  app-infra:
    external: true
