---
- name: Ensure syslog group exists for OS hardening compatibility
  ansible.builtin.group:
    name: syslog
    state: present
  become: true

- name: Firewall
  block:
  - name: Allow HTTP in iptables
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "80"
      ctstate: NEW
      jump: ACCEPT
      action: insert
    become: true
    notify: Save iptables rules

  - name: Allow HTTPS in iptables
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "443"
      ctstate: NEW
      jump: ACCEPT
      action: insert
    become: true
    notify: Save iptables rules

  - name: Allow HTTP in ip6tables
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "80"
      ctstate: NEW
      jump: ACCEPT
      action: insert
      ip_version: ipv6
    become: true
    notify: Save iptables rules

  - name: Allow HTTPS in ip6tables
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "443"
      ctstate: NEW
      jump: ACCEPT
      action: insert
      ip_version: ipv6
    become: true
    notify: Save iptables rules

- name: DNS
  block:
  - name: Ensure systemd-resolved is running
    ansible.builtin.systemd_service:
      name: systemd-resolved
      state: started
      enabled: yes
    become: true

  - name: Configure systemd-resolved for Google and Quad9 DNS
    ansible.builtin.lineinfile:
      path: /etc/systemd/resolved.conf
      regexp: '^#?DNS='
      line: 'DNS=8.8.8.8 8.8.4.4 9.9.9.9 149.112.112.112'
    notify: Restart systemd-resolved
    become: true

  - name: Configure systemd-resolved for ControlD and Cloudflare Fallback DNS
    ansible.builtin.lineinfile:
      path: /etc/systemd/resolved.conf
      regexp: '^#?FallbackDNS='
      line: 'FallbackDNS=76.76.2.0 76.76.10.0 1.1.1.1 1.0.0.1'
    notify: Restart systemd-resolved
    become: true

  - name: Configure systemd-resolved for DNSOverTLS
    ansible.builtin.lineinfile:
      path: /etc/systemd/resolved.conf
      regexp: '^#?DNSOverTLS='
      line: 'DNSOverTLS=no'
    notify: Restart systemd-resolved
    become: true

  - name: Configure systemd-resolved for Cache
    ansible.builtin.lineinfile:
      path: /etc/systemd/resolved.conf
      regexp: '^#?Cache='
      line: 'Cache=yes'
    notify: Restart systemd-resolved
    become: true

  - name: Configure systemd-resolved for Domain
    ansible.builtin.lineinfile:
      path: /etc/systemd/resolved.conf
      regexp: '^#?Domain='
      line: "Domain={{ dns_search_domain }}"
    notify: Restart systemd-resolved
    become: true
    when: dns_search_domain | default('') | length > 0
