---
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.11.4@sha256:9591b13f13843c7721c2b8eaf7382846c81b3ffe126526d1888d1fed50c6a33f
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    ports:
      - "127.0.0.1:3005:8080"
    volumes:
      - open_webui:/app/backend/data
    env_file:
      - .env
    networks:
      - app-infra

volumes:
  open_webui:
networks:
  app-infra:
    external: true
