services:
  cobalt-api:
    image: ghcr.io/imputnet/cobalt:11.7.1
    container_name: cobalt-api
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    env_file: .env
    networks:
      - app-infra
    volumes:
      - ./keys.json:/app/keys.json:ro
      - ./cookies.json:/cookies.json

networks:
  app-infra:
    external: true
