---
- name: Include borgbase.ansible_role_borgbackup role
  include_role:
    name: borgbase.ansible_role_borgbackup
  vars:
    borg_source_directories:
      - "/home"
      - "/etc"
    borg_exclude_patterns:
      - "/home/anatoli"
      - "/home/clp" 
      - "/home/mysql"
      - "*.pyc"
      - "*.tmp"
      - "*/.cache"
      - "*/.thumbnails"
    borgmatic_hooks:
      mariadb_databases:
        - name: all
          username: "{{ mysql_user }}"
          password: "{{ mysql_password }}"
          options: "--single-transaction --routines --triggers"
      healthchecks:
        ping_url: "{{ borg_heartbeat_url }}"
    borg_ssh_key_file_path: ~/.ssh/thundersquared_borg_ed25519
    borg_ssh_command: "ssh -i {{ borg_ssh_key_file_path }} -p 23"