---
scheduled_run: false
nginx_dh_size: 4096
os_user_pw_ageing: false
sftp_enabled: true
ssh_print_last_log: true
ssh_permit_root_login: "without-password"
ssh_permit_tunnel: "yes"
sysctl_overwrite:
  net.ipv4.ip_forward: 1
