---
scheduled_run: false
nginx_dh_size: 4096
os_user_pw_ageing: false
os_auth_pam_passwdqc_enable: false
sftp_enabled: true
ssh_print_last_log: true
ssh_permit_root_login: "without-password"
ssh_permit_tunnel: "yes"
ssh_client_password_login: true
ssh_server_password_login: true
sshd_authenticationmethods: "publickey,password"
sysctl_overwrite:
  net.ipv4.ip_forward: 1
  vm.swappiness: 5
  net.core.rmem_max: 7500000
  net.core.wmem_max: 7500000
