services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_METRICS=localhost:60123
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "--metrics", "localhost:60123", "ready"]
      start_period: 30s
      interval: 30s
      retries: 3
      timeout: 10s
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - app-infra

networks:
  app-infra:
    external: true
