services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - app-infra

networks:
  app-infra:
    external: true
