---
- name: Reload nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded
  become: true

- name: Restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
  become: true
