---
- name: Restart systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: restarted
  become: true

- name: Restart logrotate.timer
  ansible.builtin.systemd_service:
    name: logrotate.timer
    state: restarted
    daemon_reload: yes
  become: true
