---
services:
  database:
    image: docker.io/library/postgres:18-alpine@sha256:d3e1620b530c944afa6e887d22eb899824da68e19c52024bf98f5220c88a65b2
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 10s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - authentik

  server:
    image: ghcr.io/thundersquared/authentik:2026.8.1@sha256:09499f66c670081ea27df2c76cb8d5547b2619a1b80579a2ae5105fc37dc6d99
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    command: server
    volumes:
      - ./data:/data
      - ./custom-templates:/templates
    env_file:
      - .env
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9443:9443"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - authentik
      - app-infra

  worker:
    image: ghcr.io/thundersquared/authentik:2026.8.1@sha256:09499f66c670081ea27df2c76cb8d5547b2619a1b80579a2ae5105fc37dc6d99
    restart: unless-stopped
    command: worker
    user: root
    volumes:
      - ./data:/data
      - ./custom-templates:/templates
      - ./certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - authentik

volumes:
  database:
    driver: local

networks:
  authentik:
    driver: bridge
  app-infra:
    external: true
