---
- name: Restart containers
  community.docker.docker_compose_v2:
    project_src: "/opt/containers/{{ item }}"
    state: restarted
  loop: "{{ docker_stacks.keys() | list }}"
  when: docker_stacks | length > 0
