services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.11.3@sha256:41daa0cf2561a5d4c8d1ff31ee2a98d93ab4d3ac2605cac69366ff6a3374a933
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    ports:
      - "127.0.0.1:3004:8080"
    volumes:
      - /home/ollama:/root/.ollama
      - open_webui:/app/backend/data
    env_file:
      - .env
    networks:
      - app-infra

volumes:
  open_webui:

networks:
  app-infra:
    external: true
