---
services:
  postgres:
    image: postgres:18-alpine@sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 10s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      PGDATA: /var/lib/postgresql/18/docker
    volumes:
      - postgres:/var/lib/postgresql
    env_file:
      - .postgres.env
    networks:
      - n8n

  n8n:
    image: ghcr.io/thundersquared/n8n:2.32.7@sha256:2c7af01a4a620d8440de7408632832535269d23734a636f457d6f8ddb14d1d9c
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    ports:
      - "127.0.0.1:3004:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - n8n
      - app-infra

  runner:
    image: n8nio/runners:2.33.3@sha256:6421ace9b7d8fe4f29217865779aa7e8d01280438a7533bc2f4218be808a6511
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    env_file:
      - .runner.env
    depends_on:
      - n8n
    networks:
      - n8n

volumes:
  postgres:
  n8n_data:

networks:
  n8n:
  app-infra:
    external: true
