---
services:
  postgres:
    image: postgres:18-alpine@sha256:d3e1620b530c944afa6e887d22eb899824da68e19c52024bf98f5220c88a65b2
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 10s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      PGDATA: /var/lib/postgresql/18/docker
    volumes:
      - postgres:/var/lib/postgresql
    env_file:
      - .postgres.env
    networks:
      - n8n

  n8n:
    image: ghcr.io/thundersquared/n8n:2.38.7@sha256:d24386fa74617214c06fba8f5628a5f93750ca5daec3b15e5b36626ea4b93353
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    ports:
      - "127.0.0.1:3004:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - n8n
      - app-infra

  runner:
    image: n8nio/runners:2.39.4@sha256:6af63a7b0c0cde47993f66e46307528be44f36135d9c7a0fb7cfa38798a85a2f
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    env_file:
      - .runner.env
    depends_on:
      - n8n
    networks:
      - n8n

volumes:
  postgres:
  n8n_data:

networks:
  n8n:
  app-infra:
    external: true
