---
services:
  postgres:
    image: postgres:18-alpine@sha256:d3e1620b530c944afa6e887d22eb899824da68e19c52024bf98f5220c88a65b2
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 10s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      PGDATA: /var/lib/postgresql/18/docker
    volumes:
      - postgres:/var/lib/postgresql
    env_file:
      - .postgres.env
    networks:
      - n8n

  n8n:
    image: ghcr.io/thundersquared/n8n:2.37.7@sha256:8ebccd4d1a20896c40c2f2c68c1e96c35087ac6a03cd9a5e95572f1b3f2da4d1
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    ports:
      - "127.0.0.1:3004:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - n8n
      - app-infra

  runner:
    image: n8nio/runners:2.38.3@sha256:c489d0d207904a4d54a4f8c2a85e15e48d735521a98330f5862e81e181a8c207
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    env_file:
      - .runner.env
    depends_on:
      - n8n
    networks:
      - n8n

volumes:
  postgres:
  n8n_data:

networks:
  n8n:
  app-infra:
    external: true
