services:
  database:
    image: mysql:8.4@sha256:8dbcf531a03aade657e181b9cf2f1d1803ce621a1d55610cb44cb531ab7d7db6
    env_file: .env
    cap_add:
      - SYS_NICE
    volumes:
      - database:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD --silent || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
    networks:
      - fleet
    restart: unless-stopped

  kv:
    image: valkey/valkey:9-alpine@sha256:ee91f7a174ac4d6a6b0685b3a60e321f0a9dbbb691f9b0e285be2ba1d1be8328
    command: ["valkey-server", "--appendonly", "yes"]
    networks:
      - fleet
    restart: unless-stopped
    volumes:
      - kv:/data
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 12

  fleet-init:
    image: alpine:3.24@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
    volumes:
      - logs:/logs
      - data:/fleet
      - vulndb:/vulndb
    command: sh -c "chown -R 100:101 /logs /fleet /vulndb"

  fleet:
    image: ghcr.io/thundersquared/fleet:4.89.1@sha256:4725a16788884cfd91cf9d6d1d36bfef935ea6dce873275a13b3a7edd225f34f
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    depends_on:
      database:
        condition: service_healthy
      kv:
        condition: service_healthy
      fleet-init:
        condition: service_completed_successfully
    command: sh -c "/usr/bin/fleet prepare db --no-prompt && /usr/bin/fleet serve"
    ports:
      - "127.0.0.1:3002:${FLEET_SERVER_PORT}"
    env_file: .env
    volumes:
      - logs:/logs
      - data:/fleet
      - vulndb:/vulndb
    networks:
      - app-infra
      - fleet
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${FLEET_SERVER_PORT}/healthz"]
      interval: 10s
      timeout: 5s
      retries: 12
    restart: unless-stopped

volumes:
  database:
  logs:
  data:
  vulndb:
  kv:
networks:
  app-infra:
    external: true
  fleet:
    driver: bridge
