name: Deploy Infrastructure with Ansible
on:
  workflow_dispatch:
    inputs:
      target_node:
        description: 'Node name (e.g., web8, node2)'
        required: true
        type: choice
        options:
          - web8
          # Add more node names as needed
jobs:
  run-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
      - name: Set node secrets and playbook folder
        env:
          NODE: ${{ github.event.inputs.target_node }}
          HOST: ${{ secrets[format('{0}_HOST', github.event.inputs.target_node)] }}
          USER: ${{ secrets[format('{0}_USER', github.event.inputs.target_node)] }}
          KEY: ${{ secrets[format('{0}_KEY', github.event.inputs.target_node)] }}
        run: |
          echo "TARGET_HOST=$HOST" >> $GITHUB_ENV
          echo "ANSIBLE_USER=$USER" >> $GITHUB_ENV
          echo "ANSIBLE_SSH_PRIVATE_KEY=$KEY" >> $GITHUB_ENV
          echo "PLAYBOOK_FOLDER=$NODE" >> $GITHUB_ENV
      - name: Setup SSH key
        run: |
          echo "$ANSIBLE_SSH_PRIVATE_KEY" | base64 --decode > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Add host to inventory
        run: |
          echo "$TARGET_HOST ansible_user=$ANSIBLE_USER ansible_ssh_private_key=~/.ssh/id_rsa" > inventory
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory $PLAYBOOK_FOLDER/ansible/playbook.yml --private-key ~/.ssh/id_rsa
